name: Lint and test

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - '**'
      - '!main'
    paths-ignore:
      - '**.md'
      - '**/test_readme.py'

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.1
    - uses: actions/setup-python@v5.2.0
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Ruff
      run: poetry run ruff check src/

    - name: Flake8
      run: poetry run flake8 src/

    - name: Mypy
      run: poetry run mypy src/

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4.2.1
    - uses: actions/setup-python@v5.2.0
      with:
        python-version: ${{ matrix.version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Run tests
      run: poetry run python tests/test.py
    - name: Run tests for v1
      run: poetry run python tests/test_v1.py
    - name: Run tests for v2
      run: poetry run python tests/test_v2.py
    - name: Run tests for just a temporary little experiment
      run: poetry run python tests/test_just_a_temp_little_experiment.py
    - name: Run tests for the high school solution
      run: poetry run python tests/test_high_school.py
    - name: Run tests for the todo version
      run: poetry run python tests/test_todo.py
