name: Test README.md, wtf?!

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - '**'
      - '!main'
    paths:
      - '**.md'
      - '**/test_readme.py'

permissions:
  contents: read

jobs:
  readme:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.1
    - uses: actions/setup-python@v5.2.0
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Run tests for readme
      run: poetry run python tests/test_readme.py
